from odoo import _, models

from .odomate_hr_salary_advance import ADVANCE_INPUT_CODE


class HrPayslip(models.Model):
    _inherit = "hr.payslip"

    def _get_advance_deduction_vals(self, employee, contract, date_to):
        """Build the ``ADV_DEDUCT`` input vals for every recoverable advance.

        Shared by ``get_inputs`` (the onchange path) and ``compute_sheet``
        (the batch path), so the two can never disagree on which advances
        contribute or for how much. Only advances that have actually been
        disbursed contribute, and only to a payslip whose period ends on or
        after the disbursement date. Approved but unpaid, refused, cancelled
        and closed advances contribute nothing.
        """
        if not employee or not contract or not date_to:
            return []

        advances = self.env["odomate.hr.salary.advance"].sudo().search([
            ("employee_id", "=", employee.id),
            ("state", "=", "paid"),
            ("payment_date", "!=", False),
            ("payment_date", "<=", date_to),
        ], order="id")
        vals_list = []
        sequence = 100
        for advance in advances:
            if advance.currency_id.compare_amounts(advance.outstanding_amount, 0) <= 0:
                continue
            sequence += 1
            vals_list.append({
                "name": _("Salary Advance Deduction"),
                "code": ADVANCE_INPUT_CODE,
                "amount": advance.outstanding_amount,
                "contract_id": contract.id,
                "sequence": sequence,
                "advance_id": advance.id,
            })
        return vals_list

    def get_inputs(self, contracts, date_from, date_to):
        """Append one ``ADV_DEDUCT`` input per recoverable advance.

        Used by the onchange path (e.g. the contract/date onchange on the
        payslip form). See ``_get_advance_deduction_vals`` for the shared
        eligibility logic.
        """
        res = super().get_inputs(contracts, date_from, date_to)
        if not date_to:
            return res

        employee = self[:1].employee_id or contracts[:1].employee_id
        contract = contracts[:1] or self[:1].contract_id
        res += self._get_advance_deduction_vals(employee, contract, date_to)
        return res

    def _sync_advance_deduction_lines(self):
        """Rebuild this payslip's own ``ADV_DEDUCT`` lines from scratch.

        Every input line carrying this module's distinct ``ADV_DEDUCT`` code
        is removed — not merely the ones still tagged with an ``advance_id``.
        The form onchange emits a correctly-tagged line, but the standard
        "Other Inputs" list view does not expose ``advance_id``, so the web
        client silently drops that value on save and the line is persisted
        with ``advance_id = False``. Matching on ``advance_id`` alone would
        leave that orphan behind and the freshly-added tagged line would then
        double the deduction. Because ``ADV_DEDUCT`` is deliberately unique to
        this module (never shared with the loan module's ``LOAN_REPAY``), any
        line bearing it is ours to rebuild; input lines belonging to other
        modules or added by hand are left untouched. Safe to call more than
        once: each call replaces the prior set rather than appending to it.
        """
        self.ensure_one()
        stale = self.input_line_ids.filtered(
            lambda line: line.advance_id or line.code == ADVANCE_INPUT_CODE
        )
        if stale:
            stale.unlink()
        contract = self._get_employee_contracts()[:1]
        vals_list = self._get_advance_deduction_vals(
            self.employee_id, contract, self.date_to
        )
        if vals_list:
            self.write({"input_line_ids": [(0, 0, vals) for vals in vals_list]})

    def compute_sheet(self):
        """Ensure the ``ADV_DEDUCT`` deduction reaches batch-generated payslips.

        OCA payroll's ``compute_sheet`` (the batch/production path) never
        calls ``get_inputs`` — that method only fires from form onchanges —
        so a payslip generated by a batch run would otherwise never receive
        the advance deduction. Payslips already ``done`` or ``cancel`` are
        left untouched; recovery bookkeeping stays in ``action_payslip_done``.
        """
        for payslip in self.filtered(lambda p: p.state in ("draft", "verify")):
            payslip._sync_advance_deduction_lines()
        return super().compute_sheet()

    def action_payslip_done(self):
        """Recover the confirmed deduction, then hand back to payroll.

        The amounts are snapshotted *before* ``super()`` so an implementation
        that rebuilds input lines on confirm cannot silently drop them, and only
        payslips actually transitioning into ``done`` are collected — a second
        confirm of an already-done payslip recovers nothing.
        """
        recoveries = []
        for payslip in self:
            if payslip.state == "done":
                continue
            for line in payslip.input_line_ids:
                if line.advance_id and line.code == ADVANCE_INPUT_CODE and line.amount > 0:
                    recoveries.append((line.advance_id, line.amount))

        res = super().action_payslip_done()

        for advance, amount in recoveries:
            advance._register_recovery(amount)
        return res
